name: Run Python Unit Tests on Push

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run passgen tests
        run: |
          python -m unittest discover -s . -p 'test_passgen.py'
      - name: Run decode_pass tests
        run: |
          python -m unittest discover -s . -p 'test_decode_pass.py'
